site:
  title: KIParla documentation
  start_page: portal::index.adoc
content:
  sources:
    - url: https://github.com/KIParla/docs.git
      branches: [main]
      start_path: docs
    - url: https://github.com/KIParla/KIP.git
      branches: [main]
      tags: ['v*']
      start_path: docs
    - url: https://github.com/KIParla/KIPasti.git
      branches: [main]
      tags: ['v*']
      start_path: docs
    - url: https://github.com/KIParla/ParlaBO.git
      branches: [main]
      tags: ['v*']
      start_path: docs
    - url: https://github.com/KIParla/ParlaTO.git
      branches: [main]
      tags: ['v*']
      start_path: docs
    - url: https://github.com/KIParla/KIParla-collection.git
      branches: [main]
      start_path: docs
    - url: https://github.com/KIParla/tools.git
      branches: [main]
      start_path: docs
    - url: https://github.com/KIParla/lemmatization-project.git
      branches: [main]
      start_path: docs
    - url: https://github.com/KIParla/KIParla-Forest.git
      branches: [main]
      start_path: docs

antora:
  extensions:
    - '@antora/lunr-extension'

ui:
  bundle:
    url: https://github.com/KIParla/antora-ui/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll


output:
  dir: build/site
